#!/bin/bash -e

# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

path="${1#file://}"
identity="${2}"

if [ -z "${path}" ]; then
  echo "No file path provided." >&2
  echo "Usage:" >&2
  echo "  rvcs-pull-file file://<PATH> <IDENTITY>" >&2
  exit 1
fi

if [ -z "${identity}" ]; then
  echo "No identity provided." >&2
  echo "Usage:" >&2
  echo "  rvcs-pull-file file://<PATH> <IDENTITY>" >&2
  exit 1
fi

bundleName="$(echo "${identity}" | shasum -a 256 | cut -d ' ' -f 1)-bundle.zip"
bundlePath="${path}/${bundleName}"
if [ ! -f "${bundlePath}" ]; then
  echo "File ${bundlePath} does not exist..." >&2
  exit 0
fi

rvcs import "${bundlePath}" >&2
unzip -p "${bundlePath}" "metadata/signature" | tr -d "[:space:]"
for previousBundle in $(unzip -p "${bundlePath}" "metadata/previous"); do
  additional=$(rvcs import -v "${previousBundle}")
  if [ "${additional}" == "" ]; then
    exit 0
  fi
done
